#!/usr/bin/env python3
"""Rebuild the corpus index: _index/catalog.json + _index/INDEX.md.

Usage: python3 build_index.py <corpus_path>
Scans <corpus>/transcripts/**/*.md frontmatter.
"""
import os, sys, json, re, glob
from collections import Counter, defaultdict

CANON = ["내부-주간회의", "내부-전략", "내부-1on1", "외부-파트너", "외부-고객영업",
         "외부-투자IR", "강연-세미나", "인터뷰", "개인-통화", "기타"]
CAT_MAP = {"내부-회의": "내부-전략", "회의": "내부-전략", "내부": "내부-전략",
           "외부": "외부-파트너", "파트너": "외부-파트너", "투자": "외부-투자IR",
           "IR": "외부-투자IR", "강연": "강연-세미나", "세미나": "강연-세미나",
           "통화": "개인-통화"}

def parse_fm(text):
    m = re.match(r'^---\s*\n(.*?)\n---\s*\n', text, re.S)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        mm = re.match(r'^(\w+):\s*(.*)$', line)
        if not mm:
            continue
        k, v = mm.group(1), mm.group(2).strip().strip('"')
        if v.startswith('[') and v.endswith(']'):
            v = [x.strip().strip('"') for x in v[1:-1].split(',') if x.strip()]
        fm[k] = v
    return fm

def main():
    corpus = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.getcwd()
    tdir = os.path.join(corpus, "transcripts")
    idx = os.path.join(corpus, "_index")
    os.makedirs(idx, exist_ok=True)

    rows = []
    for p in sorted(glob.glob(os.path.join(tdir, "**", "*.md"), recursive=True)):
        try:
            fm = parse_fm(open(p, encoding="utf-8").read())
        except Exception:
            continue
        cat = CAT_MAP.get(str(fm.get("category", "기타")).strip(),
                          str(fm.get("category", "기타")).strip())
        if cat not in CANON:
            cat = "기타"
        rows.append({
            "title": fm.get("title", ""),
            "date": str(fm.get("date", "")),
            "category": cat,
            "participants": fm.get("participants", []) if isinstance(fm.get("participants"), list) else [],
            "source_id": fm.get("source_id", ""),
            "duration_min": int(fm["duration_min"]) if str(fm.get("duration_min", "")).isdigit() else None,
            "transcribed_by": fm.get("transcribed_by", ""),
            "part": fm.get("part", ""),
            "path": os.path.relpath(p, corpus),
            "vault_link": os.path.splitext(os.path.basename(p))[0],
        })

    rows.sort(key=lambda r: (r["date"], r["title"]), reverse=True)
    json.dump(rows, open(os.path.join(idx, "catalog.json"), "w"),
              ensure_ascii=False, indent=1)

    bycat = Counter(r["category"] for r in rows)
    bymon = Counter(r["date"][:7] for r in rows if r["date"])
    total_min = sum(r["duration_min"] or 0 for r in rows)

    L = ["# Meeting Corpus Index", "",
         f"> {len(rows)} transcripts · ~{total_min // 60}h total · auto-generated by build_index.py", "",
         "## By category", "", "| category | count |", "|---|---|"]
    for c in CANON:
        if bycat.get(c):
            L.append(f"| {c} | {bycat[c]} |")
    L += ["", "## By month", "", "| month | count |", "|---|---|"]
    for m in sorted(bymon, reverse=True):
        L.append(f"| {m} | {bymon[m]} |")
    L += ["", "---", "## All transcripts (by category, newest first)"]
    groups = defaultdict(list)
    for r in rows:
        groups[r["category"]].append(r)
    for c in CANON:
        if not groups.get(c):
            continue
        L += ["", f"### {c} ({len(groups[c])})", ""]
        for r in sorted(groups[c], key=lambda x: x["date"], reverse=True):
            parts = ", ".join(r["participants"][:4]) if r["participants"] else ""
            dur = f'{r["duration_min"]}min' if r["duration_min"] else ""
            extra = " · ".join(x for x in (dur, parts) if x)
            L.append(f'- `{r["date"]}` [[{r["vault_link"]}|{r["title"]}]]' + (f' · {extra}' if extra else ''))
    open(os.path.join(idx, "INDEX.md"), "w", encoding="utf-8").write("\n".join(L))
    print(f"OK: {len(rows)} entries → _index/catalog.json + _index/INDEX.md")
    print("categories:", dict(bycat))

    sid_paths = defaultdict(list)
    for r in rows:
        if r["source_id"]:
            # split recordings (_part1/_part2) legitimately share a source_id
            sid_paths[(r["source_id"], r["part"])].append(r["path"])
    dups = {k: v for k, v in sid_paths.items() if len(v) > 1}
    if dups:
        print(f"WARN: {len(dups)} source_ids appear in multiple files (same recording "
              "saved twice — keep one, delete the other):")
        for (sid, _part), paths in list(dups.items())[:8]:
            print(f"    {sid}: " + " | ".join(paths))
        if len(dups) > 8:
            print(f"    … and {len(dups) - 8} more")

if __name__ == "__main__":
    main()
